// tools/pet2lvgl/Program.cs
// Slice a green-screen spritesheet into frames, chroma-key + despill, downscale,
// emit LVGL v9 RGB565A8 C arrays (lv_image_dsc_t) plus QA PNGs.
//
// Build: csc /nologo /optimize+ /out:pet2lvgl.exe /r:System.Drawing.dll Program.cs
// Run:   pet2lvgl.exe --input sheet.png --cols 4 --rows 4 --out 96
//          --map "idle=0,running=2,done=1,alert=3"
//          --out-c main/pet_frames.c --out-h main/pet_frames.h --qa-dir frames-qa
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;

internal static class Program
{
    private static string Arg(string[] a, string name, string def)
    {
        for (int i = 0; i + 1 < a.Length; i++)
            if (a[i] == name) return a[i + 1];
        return def;
    }

    private static int Main(string[] argv)
    {
        string input = Arg(argv, "--input", null);
        if (input == null) { Console.Error.WriteLine("missing --input"); return 2; }
        int cols = int.Parse(Arg(argv, "--cols", "4"), CultureInfo.InvariantCulture);
        int rows = int.Parse(Arg(argv, "--rows", "4"), CultureInfo.InvariantCulture);
        int outSize = int.Parse(Arg(argv, "--out", "96"), CultureInfo.InvariantCulture);
        string outC = Arg(argv, "--out-c", null);
        string outH = Arg(argv, "--out-h", null);
        string qaDir = Arg(argv, "--qa-dir", null);
        string mapSpec = Arg(argv, "--map", "idle=0,running=1,done=2,alert=3");

        var order = new List<string>();
        var rowOf = new Dictionary<string, int>();
        foreach (var part in mapSpec.Split(','))
        {
            var kv = part.Split('=');
            if (kv.Length != 2) { Console.Error.WriteLine("bad --map: " + part); return 2; }
            order.Add(kv[0].Trim());
            rowOf[kv[0].Trim()] = int.Parse(kv[1].Trim(), CultureInfo.InvariantCulture);
        }

        using (var sheet = new Bitmap(input))
        {
            int cellW = sheet.Width / cols;
            int cellH = sheet.Height / rows;
            Console.WriteLine(string.Format("sheet {0}x{1} cell {2}x{3} out {4}",
                sheet.Width, sheet.Height, cellW, cellH, outSize));

            var sb = new StringBuilder();
            sb.Append("// AUTO-GENERATED by tools/pet2lvgl. Do not edit.\n");
            sb.Append("#include \"pet_frames.h\"\n\n");
            var sbH = new StringBuilder();
            sbH.Append("// AUTO-GENERATED by tools/pet2lvgl. Do not edit.\n#pragma once\n#include \"lvgl.h\"\n\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

            int frameBytes = outSize * outSize * 3;
            var qa = new Bitmap(cols * outSize, rows * outSize, PixelFormat.Format32bppArgb);

            foreach (var state in order)
            {
                int row = rowOf[state];
                sb.Append(string.Format("// state {0}: row {1}\n", state, row));
                for (int c = 0; c < cols; c++)
                {
                    byte[] data;
                    using (var keyed = RenderCell(sheet, c * cellW, row * cellH, cellW, cellH, outSize, out data))
                    {
                        using (var g = Graphics.FromImage(qa))
                            g.DrawImage(keyed, new Rectangle(c * outSize, row * outSize, outSize, outSize));

                        string name = "pet_" + state + "_" + c;
                        sb.Append("static const uint8_t " + name + "_map[] = {\n");
                        for (int i = 0; i < data.Length; i++)
                        {
                            if (i % 16 == 0) sb.Append("  ");
                            sb.Append("0x").Append(data[i].ToString("x2"));
                            if (i != data.Length - 1) sb.Append(',');
                            if (i % 16 == 15 || i == data.Length - 1) sb.Append('\n');
                        }
                        sb.Append("};\n\n");
                        sb.Append("static const lv_image_dsc_t " + name + " = {\n");
                        sb.Append("  .header.magic = LV_IMAGE_HEADER_MAGIC,\n");
                        sb.Append("  .header.cf = LV_COLOR_FORMAT_RGB565A8,\n");
                        sb.Append("  .header.w = " + outSize + ",\n");
                        sb.Append("  .header.h = " + outSize + ",\n");
                        sb.Append("  .header.stride = " + (outSize * 2) + ",\n");
                        sb.Append("  .data_size = " + frameBytes + ",\n");
                        sb.Append("  .data = " + name + "_map,\n};\n\n");
                    }
                }
                sb.Append("const void *pet_" + state + "_frames[] = {");
                for (int c = 0; c < cols; c++) sb.Append(" &pet_" + state + "_" + c + ",");
                sb.Append(" };\n");
                sb.Append("const int pet_" + state + "_count = " + cols + ";\n\n");
                sbH.Append("extern const void *pet_" + state + "_frames[];\nextern const int pet_" + state + "_count;\n");
            }

            sbH.Append("\n#ifdef __cplusplus\n}\n#endif\n");

            if (outC != null) File.WriteAllText(outC, sb.ToString(), new UTF8Encoding(false));
            if (outH != null) File.WriteAllText(outH, sbH.ToString(), new UTF8Encoding(false));
            if (qaDir != null)
            {
                Directory.CreateDirectory(qaDir);
                qa.Save(Path.Combine(qaDir, "contact-sheet.png"), ImageFormat.Png);
            }
            qa.Dispose();
            Console.WriteLine("wrote " + outC + " / " + outH);
        }
        return 0;
    }

    private static Bitmap RenderCell(Bitmap sheet, int sx, int sy, int sw, int sh, int outSize, out byte[] rgb565a8)
    {
        var dst = new Bitmap(outSize, outSize, PixelFormat.Format32bppArgb);
        using (var g = Graphics.FromImage(dst))
        {
            g.InterpolationMode = InterpolationMode.HighQualityBicubic;
            g.PixelOffsetMode = PixelOffsetMode.HighQuality;
            g.SmoothingMode = SmoothingMode.HighQuality;
            g.CompositingQuality = CompositingQuality.HighQuality;
            g.DrawImage(sheet,
                new Rectangle(0, 0, outSize, outSize),
                new Rectangle(sx, sy, sw, sh),
                GraphicsUnit.Pixel);
        }

        var rect = new Rectangle(0, 0, outSize, outSize);
        var bits = dst.LockBits(rect, ImageLockMode.ReadWrite, PixelFormat.Format32bppArgb);
        int stride = bits.Stride;
        byte[] px = new byte[stride * outSize];
        Marshal.Copy(bits.Scan0, px, 0, px.Length);

        byte[] color = new byte[outSize * outSize * 2];
        byte[] alpha = new byte[outSize * outSize];

        for (int y = 0; y < outSize; y++)
        {
            for (int x = 0; x < outSize; x++)
            {
                int o = y * stride + x * 4;
                int b = px[o + 0], gg = px[o + 1], r = px[o + 2];
                int maxRB = Math.Max(r, b);
                int greenness = gg - maxRB;

                int a;
                if (greenness <= 12) a = 255;
                else if (greenness >= 60) a = 0;
                else a = 255 * (60 - greenness) / 48;

                if (gg > maxRB) gg = maxRB;

                px[o + 0] = (byte)b; px[o + 1] = (byte)gg; px[o + 2] = (byte)r; px[o + 3] = (byte)a;

                int idx = y * outSize + x;
                int r5 = (r >> 3) & 0x1F, g6 = (gg >> 2) & 0x3F, b5 = (b >> 3) & 0x1F;
                int v = (r5 << 11) | (g6 << 5) | b5;
                color[idx * 2 + 0] = (byte)(v & 0xFF);
                color[idx * 2 + 1] = (byte)((v >> 8) & 0xFF);
                alpha[idx] = (byte)a;
            }
        }

        Marshal.Copy(px, 0, bits.Scan0, px.Length);
        dst.UnlockBits(bits);

        rgb565a8 = new byte[color.Length + alpha.Length];
        Buffer.BlockCopy(color, 0, rgb565a8, 0, color.Length);
        Buffer.BlockCopy(alpha, 0, rgb565a8, color.Length, alpha.Length);
        return dst;
    }
}
