// AUTO-GENERATED by tools/pet2lvgl. Do not edit.
#pragma once
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const void *pet_idle_frames[];
extern const int pet_idle_count;
extern const void *pet_running_frames[];
extern const int pet_running_count;
extern const void *pet_done_frames[];
extern const int pet_done_count;
extern const void *pet_alert_frames[];
extern const int pet_alert_count;

#ifdef __cplusplus
}
#endif
